version: '3.8'

services:
  quotes_server:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host

  pytest:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    depends_on:
      - quotes_server
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "sleep 60 && pytest test_quotes_api.py"
